# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\untitled2.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from ClickableLineEdit import ClickableLineEdit
import keyboard
import settings


class Ui_Binding(object):
    def setupUi(self, Binding_Dialog):
        Binding_Dialog.setObjectName("Binding_Dialog")
        Binding_Dialog.resize(311, 371)
        self.verticalLayoutWidget = QtWidgets.QWidget(Binding_Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 291, 341))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_0 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_0.setFont(font)
        self.label_0.setObjectName("label_0")
        self.horizontalLayout_10.addWidget(self.label_0)
        self.lineEdit_0 = ClickableLineEdit(self.verticalLayoutWidget)
        self.lineEdit_0.setObjectName("lineEdit_0")
        self.horizontalLayout_10.addWidget(self.lineEdit_0)
        self.verticalLayout_10.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_1.setFont(font)
        self.label_1.setObjectName("label_1")
        self.horizontalLayout_3.addWidget(self.label_1)
        self.lineEdit_1 = ClickableLineEdit(self.verticalLayoutWidget)
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.horizontalLayout_3.addWidget(self.lineEdit_1)
        self.verticalLayout_10.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit_2 = ClickableLineEdit(self.verticalLayoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_2.addWidget(self.lineEdit_2)
        self.verticalLayout_10.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        self.lineEdit_3 = ClickableLineEdit(self.verticalLayoutWidget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_6.addWidget(self.lineEdit_3)
        self.verticalLayout_10.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.lineEdit_4 = ClickableLineEdit(self.verticalLayoutWidget)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_4.addWidget(self.lineEdit_4)
        self.verticalLayout_10.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_8.addWidget(self.label_5)
        self.lineEdit_5 = ClickableLineEdit(self.verticalLayoutWidget)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout_8.addWidget(self.lineEdit_5)
        self.verticalLayout_10.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.lineEdit_6 = ClickableLineEdit(self.verticalLayoutWidget)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.horizontalLayout_5.addWidget(self.lineEdit_6)
        self.verticalLayout_10.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_9.addWidget(self.label_7)
        self.lineEdit_7 = ClickableLineEdit(self.verticalLayoutWidget)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.horizontalLayout_9.addWidget(self.lineEdit_7)
        self.verticalLayout_10.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_7.addWidget(self.label_8)
        self.lineEdit_8 = ClickableLineEdit(self.verticalLayoutWidget)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.horizontalLayout_7.addWidget(self.lineEdit_8)
        self.verticalLayout_10.addLayout(self.horizontalLayout_7)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout.addWidget(self.label_9)
        self.lineEdit_9 = ClickableLineEdit(self.verticalLayoutWidget)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.horizontalLayout.addWidget(self.lineEdit_9)
        self.verticalLayout_10.addLayout(self.horizontalLayout)

        self.lineEdit_0.setText(settings.options['0'])
        self.lineEdit_1.setText(settings.options['1'])
        self.lineEdit_2.setText(settings.options['2'])
        self.lineEdit_3.setText(settings.options['3'])
        self.lineEdit_4.setText(settings.options['4'])
        self.lineEdit_5.setText(settings.options['5'])
        self.lineEdit_6.setText(settings.options['6'])
        self.lineEdit_7.setText(settings.options['7'])
        self.lineEdit_8.setText(settings.options['8'])
        self.lineEdit_9.setText(settings.options['9'])

        self.lineEdit_0.setReadOnly(True)
        self.lineEdit_0.clicked.connect(lambda: self.Bind(Binding_Dialog, self.lineEdit_0, self.label_0))
        self.lineEdit_1.setReadOnly(True)
        self.lineEdit_1.clicked.connect(lambda: self.Bind(Binding_Dialog, self.lineEdit_1, self.label_1))
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.clicked.connect(lambda: self.Bind(Binding_Dialog, self.lineEdit_2, self.label_2))
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.clicked.connect(lambda: self.Bind(Binding_Dialog, self.lineEdit_3, self.label_3))
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.clicked.connect(lambda: self.Bind(Binding_Dialog, self.lineEdit_4, self.label_4))
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.clicked.connect(lambda: self.Bind(Binding_Dialog, self.lineEdit_5, self.label_5))
        self.lineEdit_6.setReadOnly(True)
        self.lineEdit_6.clicked.connect(lambda: self.Bind(Binding_Dialog, self.lineEdit_6, self.label_6))
        self.lineEdit_7.setReadOnly(True)
        self.lineEdit_7.clicked.connect(lambda: self.Bind(Binding_Dialog, self.lineEdit_7, self.label_7))
        self.lineEdit_8.setReadOnly(True)
        self.lineEdit_8.clicked.connect(lambda: self.Bind(Binding_Dialog, self.lineEdit_8, self.label_8))
        self.lineEdit_9.setReadOnly(True)
        self.lineEdit_9.clicked.connect(lambda: self.Bind(Binding_Dialog, self.lineEdit_9, self.label_9))

        self.retranslateUi(Binding_Dialog)
        QtCore.QMetaObject.connectSlotsByName(Binding_Dialog)

    def retranslateUi(self, Binding_Dialog):
        _translate = QtCore.QCoreApplication.translate
        Binding_Dialog.setWindowTitle(_translate("Binding_Dialog", "Binding_Dialog"))
        self.label_0.setText(_translate("Binding_Dialog", "0)"))
        self.label_1.setText(_translate("Binding_Dialog", "1)"))
        self.label_2.setText(_translate("Binding_Dialog", "2)"))
        self.label_3.setText(_translate("Binding_Dialog", "3)"))
        self.label_4.setText(_translate("Binding_Dialog", "4)"))
        self.label_5.setText(_translate("Binding_Dialog", "5)"))
        self.label_6.setText(_translate("Binding_Dialog", "6)"))
        self.label_7.setText(_translate("Binding_Dialog", "7)"))
        self.label_8.setText(_translate("Binding_Dialog", "8)"))
        self.label_9.setText(_translate("Binding_Dialog", "9)"))

    def Bind(self, Binding_Dialog, lnedit, lbel):
        recorded = keyboard.record(until='`')
        rec = ''
        for i in range((len(recorded) - 1) // 2):
            if(i == (((len(recorded) - 1) // 2) - 1)):
                rec += str(recorded[i])[14:-6]
                continue
            rec += str(recorded[i])[14:-5] + '+ '
        settings.options[lbel.text()[:-1]] = rec.replace(' ', '')
        lnedit.setText(rec.upper())
        settings._pickling()
